### ISSUE TITLE
Missing `v0.3.5` tag

### ISSUE THREAD

**Issue by ZER0** [dusk-network/jubjub#27]
On crates.io `dusk-jubjub` is version `0.3.5`, but on github we don't have a tag for such versioning.

**Comment by CPerezz** [comment]
Was the latest version published by @vlopes11 ? Since the commit where the version is bumped was done by him.

In that case, I'm not sure if 84a59b5 or 6149dbb are the crates.io exact version. Could you provide some light and add the correct tag @vlopes11 ?

**Comment by vlopes11** [comment]
The version was published properly but the tag wasn't added by mistake.

Tag added, fixed.
