### ISSUE TITLE
JubJub Ecc signature algorithm implementation

### ISSUE THREAD

**Issue by CPerezz** [dusk-network/jubjub#29]
Needed by https://app.gitbook.com/@dusk-network/s/specs/~/drafts/-MENcVSS3XWRgFEYve_O/specifications/smart-contracts/genenesis-contracts/bid-contract/ - Extend Bid section.

Maybe that could be addressed in the keys repo that @ZER0 will work on.

Let me know your thoughts! Once we decide whether this should go into jubjub or the keys repo, this would need to be implemented.

For any questions in respect of that, please check it with @toghrulmaharramov

**Comment by Bounce23** [comment]
@toghrulmaharramov, can I get confirmation that this issue is linked to the EdDSA that needs implementing with Poseidon hash?

**Comment by Bounce23** [comment]
To clarify, @toghrulmaharramov confirmed that this is related to eddsa and the issue is now in progress.

**Comment by CPerezz** [comment]
Closed via https://github.com/dusk-network/eddsa/pull/1
