### ISSUE TITLE
Add feature for std

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/jubjub#33]
Add optional feature to work under std environment.

A possible use case is to benefit from `std::io` traits

**Comment by CPerezz** [comment]
This library was already migrated to `std`. We no longer support no_std (at least for now).

So why would we need that feature?

**Comment by vlopes11** [comment]
Currently its set to `no_std`
https://github.com/dusk-network/jubjub/blob/master/src/lib.rs#L25

**Comment by CPerezz** [comment]
Closed via #39
