### ISSUE TITLE
Expose wide bytes of scalars

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/jubjub#37]
Scalars can be reconstructed from `[u8; 64]` with a infallible implementation.

Currently we have no method to extract these bytes from the scalar. Provide a `fn to_bytes_wide(&self) -> [u8; 64]` for `Fr`

**Comment by CPerezz** [comment]
Why would you need that functionality @vlopes11 ?

**Comment by vlopes11** [comment]
This would be for non-fallible serialization and deserialization of scalars, but its not trivial converting 256 to 512. So I wouldn't prioritize this issue, if not close it.

**Comment by CPerezz** [comment]
I  think we can close since it's not needed at the moment by any of our crates.
