### ISSUE TITLE
Possible incorrect usage of getters in Extended Co-ordinate system.

### ISSUE THREAD

**Issue by kevaundray** [dusk-network/jubjub#44]
In the link below, there is a get_x, get_y, get_t1, get_t2 method. 

If these methods are needed, consider having one function to return the tuple of coordinates as in the extended co-ordinate system a point cannot be uniquely identified solely by it's x or y co-ordinate.

This could cause possible bugs, where the API user gets x, expecting it to behave the same way as the Affine co-ordinate system.  

https://github.com/dusk-network/jubjub/blob/c968497fba04a4e9afae6ff6c55ff0e7dbfd3a39/src/lib.rs#L583-605

**Comment by CPerezz** [comment]
This goes inline with #41 

I do agree that this can lead to bugs. At the same time the methods as you say are needed. We could add these functions behind a feature so that you need to add it and therefore are completely sure that you will take the risk.
