### ISSUE TITLE
Random non-zero Fr scalar

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/jubjub#45]
Currently, `Fr::random` may return a zeroed scalar.

That is problematic for many crypto functions, including our EdDSA implementation.

Create a function `Fr::random_non_zero` that is infallible and guaranteed to return non-zero `Fr`

The signature should be
`pub fn random_non_zero<T>(rand: &mut T) -> Fr where T: RngCore + CryptoRng`

**Comment by CPerezz** [comment]
The chances of getting a full_zeroed scalar out from the `random` impl is negligible. Idk why this is needed.

**Comment by Bounce23** [comment]
I agree with @CPerezz but its the small extra guarantee of security. So it can be worthwhile

**Comment by CPerezz** [comment]
As we discussed yesterday with @Bounce23 the check will be removed from the eddsa protocol and so, there's no need to have it here neither.

We should close that IMO.

**Comment by Bounce23** [comment]
As per the discussions on the past two days, this issue can now be closed. The reasons is that the we don't need to ensure we output a non zero scalar, as the probability of zero is negligible.
