### ISSUE TITLE
JubJubExtended - No `Default` implementation

### ISSUE THREAD

**Issue by vlopes11** [dusk-network/jubjub#63]
The extended point can't ever be derived from default because it will always be an invalid point with `z = 0`.

#### Proposed solution

Remove `Default` for `JubJubExtended`

Alternatively, we can set the `Default` to be the extended form of the curve generator

**Comment by ZER0** [comment]
`Default` for `JubJubExtended` should returns Identity (this is a breaking change).

**Comment by moCello** [comment]
`Default` for `JubJubExtended` and `JubJubAffine` both return the Identity
