### ISSUE TITLE
Adopt ZIP 216: Require Canonical Jubjub Point Encodings

### ISSUE THREAD

**Issue by str4d** [dusk-network/jubjub#82]
Jubjub was specified such that all points are strongly-typed with canonical representations. However, there is a bug in the version of the `jubjub` crate that you forked from, which allows non-canonical encodings to be silently accepted for two points:

- (0, 1), which is the identity;
- (0, -1), which is a point of order two.

We are fixing this upstream in https://github.com/zkcrypto/jubjub/pull/46; I recommend that you similarly adopt [ZIP 216](https://zips.z.cash/zip-0216) (or equivalent for your usages of Jubjub).

**Comment by CPerezz** [comment]
Hey @str4d I just noticed about this. I wasn't subscribed to the repo and did not see it. Thanks a lot for opening the issue and leave the explanation and the background. We will address it immediately. 

Thanks so much!!!
CPerezz.
